..\bin\AyaCompile Strings.mod
..\bin\AyaCompile WinBase.mod
..\bin\AyaCompile WinApi.mod
..\bin\AyaCompile ProgArgs.mod
..\bin\AyaCompile Console.mod
..\bin\AyaCompile Sys.mod
..\bin\AyaCompile Base.mod
..\bin\AyaCompile Scanner.mod
..\bin\AyaCompile SymTable.mod
..\bin\AyaCompile Generator.mod
..\bin\AyaCompile Parser.mod
..\bin\AyaCompile AyaCompile.mod