..\source\AyaCompile WinApi.mod
..\source\AyaCompile Strings.mod
..\source\AyaCompile Console.mod
..\source\AyaCompile Sys.mod
..\source\AyaCompile Base.mod
..\source\AyaCompile Scanner.mod
..\source\AyaCompile Generator.mod
..\source\AyaCompile SymTable.mod
..\source\AyaCompile Parser.mod
..\source\AyaCompile Test.mod